// Generated by https://quicktype.io

export interface Almacen {
  id?: number;
  cia: number | string;
  d_cia?: string;
  sucursal: number | string;
  d_sucursal?: string;
  almacen: number;
  descripcion: string;
}
