// Generated by https://quicktype.io

export interface AnticipoGet {
  id: number;
  cia: number;
  nombreCia: string;
  sucursal: number;
  nombreSuc: string;
  caja: number;
  fecha: string;
  no_venta: number;
  fechaMovto: string;
  idCliente: number;
  idUsuario: number;
  nombreUsr: string;
  tipoMovto: number;
  referencia: string;
  importe: number;
  observaciones: string;
  d_cliente?: string;
  id_formaPago: number;
}
