// Generated by https://quicktype.io

export interface clientesAgendadoAct {
  id : number;
  idsucursal : 	number;
  nombre : string;
  fechaVisita	: string;
  idCliente	: number;
  nombreCliente	: string;
  nombreServicio: string;
  telefono	: string;
  nombreEstilista : string;
  idProximaCitaNormal	: 	number;
  fechaProximaCitaNormal : string;	
  llamada1: boolean;
  llamada2: boolean;
  llamada3: boolean;
  idRespuesta	: 	number;
  dRespuesta	: string;
  observaciones		: string;
  fechaNuevaCita	: string;
  idServicioNuevaCita	: number;	
  ServicioNuevaCita	: string;
  idUsuarioAltaSeguimiento	: number;	
  dUsurioAltaSeguimiento	: string;
  idUsuarioSeguimiento	: number;	
  dUsurioSeguimiento : string;
}
