// Generated by https://quicktype.io

export interface CompraSeleccion {
  nombreEncargado: any;
  id_compra: number;
  cia: number;
  idSucursal: number;
  idProveedor: number;
  nombre: string;
  items: number;
  importe: number;
  Estatus: string;
  fecha?: string;
}
