// Generated by https://quicktype.io

export interface CorteA {
  FormadePago: string;
  Importe: string;
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface CorteB {
  total_Servicios: string;
  servicios_Realizados: number;
  servicios_Agendados: number;
}

// Generated by https://quicktype.io

export interface CorteC {
  Responsable: string;
  Servicio: number;
  Venta: number;
  Color: string;
  Productos: number;
}
