// Generated by https://quicktype.io

export interface CorteParcialResponse {
  sucursal: number;
  caja: number;
  corte: number;
  corte_parcial: number;
  tipo_pago: number;
  descripcion: string;
  importe: number;
}
