// Generated by https://quicktype.io

export interface CorteA {
  FormadePago: string;
  Importe: string;
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface CorteB {
  total_Servicios: string;
  servicios_Realizados: number;
  servicios_Agendados: number;
}

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface CorteC {
  fecha: string;
  Sucursal: number;
  colaborador: string;
  ventaProductos: number;
  ventaServicios: number;
  ventaTotal: number;
  porcentaje: number;
  ticketPromedio: number;
  numeroTickets: number;
  tiempoAtencion: string;
}

export interface CorteD {
clave_empleado :	string, 	
ventaServicio :	string, 	
avanceServicio :	string, 	
ventaReventa :	string, 	
avanceVenta : string, 	
cantidadColor : number, 	
cantidadProductos : number, 	
cantidadTratamietos :	number, 	
total : string, 	
porcentajeTotal : string, 	
nombre :	string, 	
resta : string,
  
}
