// Generated by https://quicktype.io

export interface CorteA {
  FormadePago: string;
  Importe: string;
}
// Generated by https://quicktype.io

export interface CorteB {
  FechaCita: string;
  DescripcionCita: string;
}
// Generated by https://quicktype.io

export interface CorteC {
  Responsable: string;
  Servicio: number;
  Venta: number;
  Color: string;
  Productos: number;
}
