// Generated by https://quicktype.io

export interface DescPorPunto {
  id?: number;
  cia: number;
  sucursal: number;
  area: number;
  depto: number;
  forma_pago: number;
  porcentaje_puntos: number;
}
