// Generated by https://quicktype.io

export interface EstilistaSucResponse {
  id: number;
  clave_empleado: string;
  status: number;
  d_estatus: string;
  nombre: string;
  fecha_nacimiento: string;
  sexo: string;
  RFC: string;
  CURP: string;
  imss: string;
  domicilio: string;
  colonia: string;
  poblacion: string;
  estado: string;
  lugar_nacimiento: string;
  codigo_postal: string;
  telefono1: string;
  telefono2: string;
  email: string;
  idDepartamento: number;
  descripcion_departamento: string;
  idPuesto: number;
  descripcion_puesto: string;
  observaciones: string;
  nivel_escolaridad: number;
  d_nivelEscolaridad: string;
  fecha_baja: string;
  motivo_baja: number;
  d_motiboBaja: string;
  motivo_baja_especificacion: string;
  fecha_alta: string;
  fecha_cambio: string;
}
