// Generated by https://quicktype.io

export interface FormaPago {
    id:              number;
    sucursal:        number;
    nombreSuc:       string;
    tipo:            number;
    descripcion:     string;
    grupo_operacion: number;
    tarjeta:         boolean;
}
