// Generated by https://quicktype.io

export interface UserResponse {
  acceso: number;
  id: number;
  cia: number;
  idDepartamento: number;
  sucursal: number;
  d_sucursal: string;
  clave_empleado: string;
  status: number;
  nombre: string;
  fecha_nacimiento: string;
  sexo: string;
  RFC: string;
  CURP: string;
  imss: string;
  domicilio: string;
  colonia: string;
  poblacion: string;
  estado: string;
  lugar_nacimiento: string;
  codigo_postal: string;
  telefono1: string;
  telefono2: string;
  email: string;
  idPuesto: number;
  observaciones: string;
  nivel_escolaridad: number;
  fecha_baja: null;
  motivo_baja: null;
  motivo_baja_especificacion: null;
  fecha_alta: string;
  fecha_cambio: string;
  clave_perfil: number;
  password: string;
}
