// Generated by https://quicktype.io

export interface Kit {
  id: number;
  idProducto: number;
  d_kit: string;
  idInsumo: number;
  d_insumo: string;
  cantidad: number;
  costo: number;
  importe: number;
}
