// Generated by https://quicktype.io

export interface MovimientoBusqueda {
  sucursal: number;
  nombreSucursal: string;
  folio: number;
  fecha: string;
  items: number;
  usuario: number;
  nombreUsuario: string;
  tipo_movto: number;
  descripcion: string;
  finalizado: boolean;
}

// Generated by https://quicktype.io

export interface MovimientoResponse {
  id: number;
  cia: number;
  sucursal: number;
  nombreSucursal: string;
  almacen: number;
  d_almacen: string;
  folio: number;
  fecha: string;
  clave_prod: number;
  d_producto: string;
  cantidad_entrada: number;
  cantidad_salida: number;
  costo: number;
  precio: number;
  tasa_iva: number;
  usuario: number;
  nombreUsuario: string;
  tipo_movto: number;
  descripcion: string;
  finalizado: boolean;
  observaciones: string;
  existencia: number;
}
