// export interface Perfil_Modulo {
//   clave_perfil: number;
//   modulo: number;
//   permiso: boolean;
// }
// Generated by https://quicktype.io

export interface Perfil_Modulo {
  id?: number;
  clave_perfil: number;
  d_perfil?: string;
  modulo: number;
  d_modulo?: string;
  permiso: boolean;
}
