export interface Traspaso {
  cia: number;
  sucursal: number;
  folio: string | number;
  fecha: string;
  clave_prod: string | number;
  d_producto?: string;
  cantidad: number | string;
  costo: number | string;
  precio: number | string;
  suc_origen: number | string;
  suc_destino: number | string;
  usuario: number | string | undefined;
  id: number;
  d_existencia?: number;
  idProducto?: string;
  almacenOrigen: number;
  almacenDestino: number;
}

// Generated by https://quicktype.io

export interface TraspasoGet {
  id: number;
  cia: number;
  sucursal: number;
  folio: number;
  fecha: string;
  idProducto: number;
  clave_prod: string;
  d_producto: string;
  cantidad: number;
  costo: number;
  precio: number;
  suc_origen: number;
  d_sucOrigen: string;
  suc_destino: number;
  d_sucDestino: string;
  usuario: number;
  usuarioTraspaso: string;
  recibido: boolean;
  fecha_recepcion: null;
  usuario_recepcion: null;
  usuarioRecepcion: string;
  cancelado: boolean;
  fecha_cancelacion: null;
  usuario_cancelacion: null;
  usuarioCancelacion: null;
  unidad_medida: number;
  d_unidadmedida: string;
  almacenOrigen?: number;
  nombreAlmOrigen?: string;
  almacenDestino?: number;
  nombreAlmDestino?: string;
}
// Generated by https://quicktype.io

// Generated by https://quicktype.io

export interface TraspasoBusqueda {
  cia: number;
  sucursal: number;
  folio: number;
  fecha: string;
  suc_origen: number;
  d_sucOrigen: string;
  suc_destino: number;
  d_sucDestino: string;
  usuario: number;
  usuarioTraspaso: string;
  recibido: boolean;
  fecha_recepcion: null | string;
  usuario_recepcion: number | null;
  usuarioRecepcion: string;
  cancelado: boolean;
  fecha_cancelacion: null;
  usuario_cancelacion: null;
  usuarioCancelacion: null;
  d_almacenOrigen?: string;
  d_almacenDestino?: string;
}
