// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface Usuario {
  idCia: any;
  id?: number;
  usuario: string;
  clave_perfil: number;
  d_perfil?: string;
  password: string;
  nombre: string;
  celular: string;
  telefono: string;
  email: string;
  fecha_alta?: string;
  fecha_act?: string;
  d_sucursal?: string;
  sucursal?: any;
}
