// Generated by https://quicktype.io

export interface VentaInsumo {
  id: number;
  id_venta: number;
  id_insumo: number;
  d_insumo?: string;
  cantidad: number;
  fechaAlta: string;
  unidadMedida: string;
  cantidadOri?: number;
  existencia?: number || string;
 
}
